### ISSUE TITLE
The table widget example is misguiding

### ISSUE THREAD

**Issue by philippelejeune01** [tui-rs-revival/ratatui#120] opened 2023-03-28 08:58 UTC
## Description

The table widget example is potentially misguiding users on the crossterm Events API. The table widget example uses the KeyCode enum in crossterm without filtering for the `KeyEventKind::Press`, which leads in events being doubled when pressing keys. It isn't a bug per se, I just don't think that was the behavior that was intended from the snippet.

line 108-115 in [this](https://github.com/tui-rs-revival/ratatui/blob/a9ba23bae8398b0add4ee647516b8e094dd29e3d/examples/table.rs) file for the exact part

**Comment by mindoodoo** [comment] 2023-03-28 15:10
What platform are you on ? I remember something about it being a platform issue

**Comment by conradludgate** [comment] 2023-03-28 15:31
I've heard reports of this problem on windows

**Comment by philippelejeune01** [comment] 2023-03-28 21:19
yes it's on windows, Is this a crossterm issue then?

**Comment by lesleyrs** [comment] 2023-04-12 17:40
It actually applies to other platforms as well if they use kitty, so I didn't use the best title my bad. But that doesn't apply to most linux users and on windows terminal it's enabled by default so it affects almost all users.

The only thing my PR does right now is simply specify the press event to avoid unintended behavior, and it will work regardless of whether the upstream crossterm PR gets merged or not.

**Closed** 2023-04-13 20:21 UTC
Labels: bug
